# Generated by Django 4.2.23 on 2025-07-12 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Document Number"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "person_type",
                    models.CharField(
                        choices=[("JURIDICAL", "Juridical"), ("PHYSICAL", "Physical")],
                        default="JURIDICAL",
                        max_length=15,
                        verbose_name="Person Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
            ],
        ),
        migrations.CreateModel(
            name="UnitMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=45, unique=True, verbose_name="Order Number"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Order Date")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Unit Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "unit_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.unitmeasure",
                        verbose_name="Unit of Measure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="orders.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="unit_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="orders.unitmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
    ]
