# Generated by Django 4.2.23 on 2025-08-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnpublishedOrder",
            fields=[],
            options={
                "verbose_name": "Unpublished Order",
                "verbose_name_plural": "Unpublished Orders",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.AddField(
            model_name="order",
            name="accounting_entry_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=75,
                null=True,
                verbose_name="Accounting Entry Number",
            ),
        ),
    ]
